/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import tempos.Tempos;

/**
 *
 * @author Thulio
 */
public class Tela extends javax.swing.JFrame {

    
    public File arquivo = null;
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) jTDados.getModel();
        jTDados.setRowSorter(new TableRowSorter(model));
        
    }

    public void lerArquivo(){
        try {
            Scanner in = new Scanner(arquivo);
            
            List<Tempos> dados = new ArrayList<Tempos>();
            
            String d = null;
            
            while (in.hasNextLine()){
                d = in.nextLine();
                Tempos t = new Tempos(Integer.parseInt(d.substring(0,3)), 
                                      Integer.parseInt(d.substring(3,5)), 
                                      Integer.parseInt(d.substring(5,8)), 
                                      d.substring(8,16), 
                                      d.substring(16,d.length()));
                
                dados.add(t);
                //System.out.println(t.toString());
            }
            
            DefaultTableModel modelo = (DefaultTableModel) jTDados.getModel();
            for (Tempos t : dados){
                modelo.addRow(new Object[]{
                        t.getReg(),
                        t.getNum_pc(),
                        t.getEquipe(),
                        t.getHora()
                         });
            }
            
            
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Escolha um arquivo com os tempos da prova!");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Escolha um arquivo com os tempos da prova!"+"(FNF)");
        } 
    }
    public void buscarDados(String equipe, String pc){
        try {
            Scanner in = new Scanner(arquivo);
            
            List<Tempos> dados = new ArrayList<Tempos>();
            
            String d = null;
            
            while (in.hasNextLine()){
                d = in.nextLine();
                
                Tempos t = new Tempos(Integer.parseInt(d.substring(0,3)), 
                                      Integer.parseInt(d.substring(3,5)), 
                                      Integer.parseInt(d.substring(5,8)), 
                                      d.substring(8,16), 
                                      d.substring(16,d.length()));
                
                
                if (pc.equals("")){
                    if (t.getEquipe() == Integer.parseInt(equipe)){
                        dados.add(t);
                    }
                }else if (equipe.equals("")){
                    if (t.getNum_pc() == Integer.parseInt(pc)){
                        dados.add(t);
                    }
                }else{
                    if (t.getNum_pc() == Integer.parseInt(pc) && t.getEquipe() == Integer.parseInt(equipe)){
                        dados.add(t);
                    }
                }
            }
            
            DefaultTableModel modelo = (DefaultTableModel) jTDados.getModel();
            modelo.setNumRows(0);
            
            for (Tempos t : dados){
                modelo.addRow(new Object[]{
                        t.getReg(),
                        t.getNum_pc(),
                        t.getEquipe(),
                        t.getHora()
                         });
            }
            
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Escolha um arquivo com os tempos da prova!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDados = new javax.swing.JTable();
        jSpinnerEquipe = new javax.swing.JSpinner();
        lblPc = new javax.swing.JLabel();
        lblEquipe1 = new javax.swing.JLabel();
        jTxtPC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTxtArquivo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelFundo.setBackground(new java.awt.Color(153, 204, 255));
        jPanelFundo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_cormed.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanelResultado.setBackground(new java.awt.Color(153, 153, 153));
        jPanelResultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REG", "PC", "EQUIPE", "HORA"
            }
        ));
        jScrollPane1.setViewportView(jTDados);

        javax.swing.GroupLayout jPanelResultadoLayout = new javax.swing.GroupLayout(jPanelResultado);
        jPanelResultado.setLayout(jPanelResultadoLayout);
        jPanelResultadoLayout.setHorizontalGroup(
            jPanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelResultadoLayout.setVerticalGroup(
            jPanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSpinnerEquipe.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jSpinnerEquipe.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblPc.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPc.setText("PC:");

        lblEquipe1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblEquipe1.setText("EQUIPE:");

        jTxtPC.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTxtArquivo.setFont(new java.awt.Font("Verdana", 0, 8)); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_white.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFundoLayout = new javax.swing.GroupLayout(jPanelFundo);
        jPanelFundo.setLayout(jPanelFundoLayout);
        jPanelFundoLayout.setHorizontalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addComponent(lblEquipe1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtPC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(jTxtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelFundoLayout.setVerticalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFundoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinnerEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPc)
                                .addComponent(jTxtPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEquipe1)
                                .addComponent(jTxtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 432, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //int pc;
        //int equipe;
        
        //if (jTxtPC.getText().isEmpty() || Integer.parseInt(jSpinnerEquipe.getValue().toString()) == 0){
            String pc = jTxtPC.getText();
            String equipe = jSpinnerEquipe.getValue().toString();
        //}else{
        //    pc = Integer.parseInt(jTxtPC.getText());
        //    equipe = Integer.parseInt(jSpinnerEquipe.getValue().toString());
        //}
        
        File arquivo = new File("dados.txt");
        
        if (equipe.equals("0") && pc.isEmpty()){
            lerArquivo();    
        
        }else if (pc.isEmpty() && !equipe.equals("0")){
                buscarDados(equipe, "");                
        }else if (!pc.isEmpty() && equipe.equals("0")){
                buscarDados("", pc);                
        }else{
                buscarDados(equipe, pc);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser jfc = new JFileChooser();
        int opt = jfc.showOpenDialog(this);
        
        if (opt == JFileChooser.APPROVE_OPTION) {
            arquivo = jfc.getSelectedFile();
            //This is where a real application would open the file.
            jTxtArquivo.setText(arquivo.getAbsolutePath());
        } else {
            jTxtArquivo.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelResultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerEquipe;
    private javax.swing.JTable jTDados;
    private javax.swing.JTextField jTxtArquivo;
    private javax.swing.JTextField jTxtPC;
    private javax.swing.JLabel lblEquipe1;
    private javax.swing.JLabel lblPc;
    // End of variables declaration//GEN-END:variables
}
